### ISSUE TITLE
IR-LED directly conntected to arduino serial-programmer connector

### ISSUE THREAD

**Issue by ep092** [Virtex7/RX5808#2]
The IR-LED is directly connected to the TX wire of the UART used for serial programming. This limits the voltage and is probably the reason for the errors at programming over bootloader.

**Comment by Virtex7** [comment]
geändert.
die LED hat jetzt einen eigenen widerstand. 
Layout muss noch angepasst werden.

**Comment by Virtex7** [comment]
auch im layout gefixt.
